#include "rectangle.h"

PyTypeObject RectangleType = {
        PyVarObject_HEAD_INIT(nullptr, 0)
        "goopylib.Rectangle",
        sizeof(RectangleObject),
        0,
        (destructor) rectangle::dealloc,
        0,
        nullptr,
        nullptr,
        nullptr,
        nullptr,
        nullptr,
        nullptr,
        nullptr,
        nullptr,
        nullptr,
        nullptr,
        nullptr,
        nullptr,
        nullptr,
        Py_TPFLAGS_DEFAULT | Py_TPFLAGS_HAVE_GC,
        "",
        (traverseproc) rectangle::traverse,
        (inquiry) rectangle::clear,
        nullptr,
        0,
        nullptr,
        nullptr,
        nullptr,
        nullptr,
        nullptr,
        nullptr,
        nullptr,
        nullptr,
        nullptr,
        0,
        (initproc) rectangle::init,
        nullptr,
        rectangle::new_,
        nullptr,
        nullptr,
        nullptr,
        nullptr,
        nullptr,
        nullptr,
        nullptr,
        nullptr,
        0,
        nullptr,
        nullptr
};
